services:
  nginx:
    image: nginx:1.27-alpine
    container_name: sites_nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:8080"
    volumes:
      # DO NOT mount nginx.conf anymore
      - ../config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../config/nginx/snippets:/etc/nginx/snippets:ro
      - ../data/sites:/srv/sites:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"      # cap to half a CPU
          memory: 256M      # plenty for static sites
        reservations:
          memory: 64M